"use client";

import { useEffect, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";

import { requestJson } from "@/lib/request-json";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Item, ItemActions, ItemContent, ItemDescription, ItemGroup, ItemTitle } from "@/components/ui/item";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
import { PhoneInput } from "@/components/ui/phone-input";
import { Skeleton } from "@/components/ui/skeleton";
import { Surface } from "@/components/ui/surface";
import { Textarea } from "@/components/ui/textarea";

type Profile = { greeting: string; tone: string; summary: string; bookingPolicy: string; voiceInstructions: string | null; smsInstructions: string | null; chatInstructions: string | null; transferMode: string; transferNumber: string | null };
type AgentResponse = { business: { id: string; name: string; defaultLocale: "en" | "fr" } | null; profile: Profile | null };

export function LiveAgentBasicSettingsSurface() {
  const { i18n, t } = useTranslation(["agent", "common"]);
  const queryClient = useQueryClient();
  const configuration = useQuery({ queryKey: ["agent"], queryFn: () => requestJson<AgentResponse>("/api/agent") });
  const [greeting, setGreeting] = useState(""); const [locale, setLocale] = useState<"en" | "fr">("en"); const [transferNumber, setTransferNumber] = useState(""); const [summary, setSummary] = useState(""); const [bookingPolicy, setBookingPolicy] = useState(""); const [voiceInstructions, setVoiceInstructions] = useState(""); const [smsInstructions, setSmsInstructions] = useState("");
  useEffect(() => { const profile = configuration.data?.profile; if (!profile) return; setGreeting(profile.greeting); setLocale(configuration.data?.business?.defaultLocale ?? "en"); setTransferNumber(profile.transferNumber ?? ""); setSummary(profile.summary); setBookingPolicy(profile.bookingPolicy); setVoiceInstructions(profile.voiceInstructions ?? ""); setSmsInstructions(profile.smsInstructions ?? ""); }, [configuration.data]);
  const save = useMutation({ mutationFn: (patch: Record<string, unknown>) => requestJson<{ profile: Profile }>("/api/agent", { method: "PATCH", body: JSON.stringify(patch) }), onSuccess: async () => { await queryClient.invalidateQueries({ queryKey: ["agent"] }); }, });
  const status = save.isSuccess ? t("agent:actions.saved") : null;

  return <div className="w-full overflow-y-auto pb-12"><div className="flex w-full flex-col gap-8"><section className="flex flex-col gap-3"><h2 className="font-heading text-sm leading-snug font-medium">{t("agent:fields.defaults.title")}</h2><Surface className="flex flex-col">
    <Item className="rounded-none border-x-0 border-t-0 border-b border-border last:border-b-0"><ItemContent><ItemTitle>{t("agent:fields.greeting.label")}</ItemTitle><ItemDescription>{t("agent:fields.greeting.hint")}</ItemDescription><div className="pt-2">{configuration.isLoading ? <Skeleton className="h-10 w-full sm:max-w-md" /> : <Input className="w-full sm:max-w-md" onChange={(event) => setGreeting(event.target.value)} placeholder={t("agent:fields.greeting.placeholder")} value={greeting} />}</div>{status ? <ItemDescription>{status}</ItemDescription> : null}</ItemContent><ItemActions className="w-full justify-end sm:w-auto"><Button disabled={save.isPending || configuration.isLoading} onClick={() => save.mutate({ greeting })} size="sm" variant="outline">{save.isPending ? t("agent:actions.saving") : t("agent:actions.save")}</Button></ItemActions></Item>
    <Item className="rounded-none border-x-0 border-t-0 border-b border-border last:border-b-0"><ItemContent><ItemTitle>{t("agent:fields.defaultLocale.label")}</ItemTitle><ItemDescription>{t("agent:fields.defaultLocale.hint")}</ItemDescription></ItemContent><ItemActions className="w-full sm:w-auto">{configuration.isLoading ? <Skeleton className="h-10 w-24" /> : <NativeSelect aria-label={t("agent:fields.defaultLocale.label")} className="w-full sm:w-[9.5ch]" onChange={(event) => { const next = event.target.value as "en" | "fr"; setLocale(next); save.mutate({ locale: next }); }} value={locale}><NativeSelectOption value="en">{t("common:language.english")}</NativeSelectOption><NativeSelectOption value="fr">{t("common:language.french")}</NativeSelectOption></NativeSelect>}</ItemActions></Item>
    <Item className="rounded-none border-x-0 border-t-0 border-b border-border last:border-b-0"><ItemContent><ItemTitle>{t("agent:fields.transferNumber.label")}</ItemTitle><ItemDescription>{t("agent:fields.transferNumber.hint")}</ItemDescription><div className="pt-2">{configuration.isLoading ? <Skeleton className="h-10 w-32" /> : <PhoneInput className="w-full min-w-0 sm:w-[12ch]" containerClassName="w-full sm:w-fit" locale={i18n.language} onChange={(value) => setTransferNumber(value ?? "")} {...(transferNumber ? { value: transferNumber } : {})} />}</div></ItemContent><ItemActions className="w-full justify-end sm:w-auto"><Button disabled={save.isPending || configuration.isLoading} onClick={() => save.mutate({ transferNumber: transferNumber || null })} size="sm" variant="outline">{save.isPending ? t("agent:actions.saving") : t("agent:actions.save")}</Button></ItemActions></Item>
  </Surface></section>
  <section className="flex flex-col gap-3"><h2 className="font-heading text-sm leading-snug font-medium">{t("agent:fields.instructions.title")}</h2><Surface className="flex flex-col"><Item className="rounded-none border-x-0 border-t-0 border-b"><ItemContent><ItemTitle>{t("agent:fields.summary.label")}</ItemTitle><ItemDescription>{t("agent:fields.summary.hint")}</ItemDescription><Textarea className="mt-2 min-h-24" onChange={(event) => setSummary(event.target.value)} value={summary} /></ItemContent></Item><Item className="rounded-none border-x-0 border-t-0 border-b"><ItemContent><ItemTitle>{t("agent:fields.bookingPolicy.label")}</ItemTitle><ItemDescription>{t("agent:fields.bookingPolicy.hint")}</ItemDescription><Textarea className="mt-2 min-h-24" onChange={(event) => setBookingPolicy(event.target.value)} value={bookingPolicy} /></ItemContent></Item><Item className="rounded-none border-x-0 border-t-0 border-b"><ItemContent><ItemTitle>{t("agent:fields.voiceInstructions.label")}</ItemTitle><Textarea className="mt-2 min-h-28" onChange={(event) => setVoiceInstructions(event.target.value)} value={voiceInstructions} /></ItemContent></Item><Item className="rounded-none border-0"><ItemContent><ItemTitle>{t("agent:fields.smsInstructions.label")}</ItemTitle><Textarea className="mt-2 min-h-28" onChange={(event) => setSmsInstructions(event.target.value)} value={smsInstructions} /></ItemContent><ItemActions className="self-end"><Button disabled={save.isPending} onClick={() => save.mutate({ summary, bookingPolicy, voiceInstructions: voiceInstructions || null, smsInstructions: smsInstructions || null })} size="sm">{save.isPending ? t("agent:actions.saving") : t("agent:actions.save")}</Button></ItemActions></Item></Surface></section></div></div>;
}
