FROM otel/opentelemetry-collector-contrib:0.158.0

ARG SERVICE_VERSION=development
LABEL org.opencontainers.image.revision=$SERVICE_VERSION

COPY docker/otel-collector/config.yaml /etc/otelcol-contrib/config.yaml

USER 10001

EXPOSE 4317 4318 13133 9464
CMD ["--config=/etc/otelcol-contrib/config.yaml"]
