import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";
import { eq } from "drizzle-orm";
import { businesses, businessMemberships, createDatabaseClient, phoneNumbers, users, withBusinessTransaction } from "@lobbystack/db";
import settings from "../public/locales/fr/settings.json" with { type: "json" };
import translations from "../public/locales/fr/agent.json" with { type: "json" };

const state = process.env.PARITY_PORT_OPERATOR_STORAGE_STATE_FR;
const userId = process.env.PARITY_OPERATOR_USER_ID;
test("service, rule and knowledge editors persist changes and enforce read-only membership", async ({ browser, baseURL }) => {
  test.skip(!state || !userId, "Requires an authenticated disposable operator fixture.");
  const database = createDatabaseClient("lobbystack_worker");
  const auth = createDatabaseClient("lobbystack_auth");
  const businessId = randomUUID();
  const context = await browser.newContext({ storageState: state!, locale: "fr" });
  const headers = { Origin: baseURL!, "Sec-Fetch-Site": "same-origin" };
  const original = (await auth.db.select({ activeBusinessId: users.activeBusinessId, phone: users.phone, phoneVerifiedAt: users.phoneVerifiedAt }).from(users).where(eq(users.id, userId!)))[0];
  try {
    await withBusinessTransaction(database.db, { businessId, actorType: "worker" }, async (tx) => {
      await tx.insert(businesses).values({ id: businessId, slug: `agent-workflows-${businessId}`, name: "Agent workflows", deploymentMode: "self_hosted_standard", timezone: "UTC", businessType: "clinic", onboardingStage: "complete" });
      await tx.insert(businessMemberships).values({ businessId, userId: userId!, role: "business_owner", status: "active" });
    });
    await auth.db.update(users).set({ activeBusinessId: businessId }).where(eq(users.id, userId!));
    const page = await context.newPage();
    await page.goto(`${baseURL}/agent/services`);
    await page.getByRole("button", { name: translations.sections.services.addKnowledge, exact: true }).click();
    const dialog = page.getByRole("dialog");
    await dialog.getByRole("button", { name: translations.actions.save, exact: true }).click();
    await expect(dialog).toBeVisible();
    expect((await (await context.request.get(`${baseURL}/api/catalog?businessId=${businessId}`)).json()).services).toHaveLength(0);
    await dialog.getByLabel(translations.sections.services.fields.title.label, { exact: true }).fill("Consultation parity");
    await dialog.getByLabel(translations.sections.services.fields.duration.label, { exact: true }).fill("45");
    await dialog.getByLabel(translations.sections.services.fields.content.label, { exact: true }).fill("Service workflow description");
    await dialog.getByRole("switch").click();
    await dialog.getByRole("button", { name: translations.actions.save, exact: true }).click();
    await expect(dialog).toBeHidden();
    const catalogUrl = `${baseURL}/api/catalog?businessId=${businessId}`;
    const saved = (await (await context.request.get(catalogUrl)).json()).services.find((service: { name: string }) => service.name === "Consultation parity");
    expect(saved).toMatchObject({ name: "Consultation parity", durationMinutes: 45, active: false });
    await page.reload();
    await page.getByText("Consultation parity", { exact: true }).click();
    await expect(dialog.getByLabel(translations.sections.services.fields.duration.label, { exact: true })).toHaveValue("45");
    await dialog.getByLabel(translations.sections.services.fields.title.label, { exact: true }).fill("Updated consultation");
    await dialog.getByRole("button", { name: translations.actions.saveChanges, exact: true }).click();
    await expect(dialog).toBeHidden();
    await page.getByRole("row").filter({ hasText: "Updated consultation" }).getByRole("button", { name: translations.actions.moreOptions }).click();
    await page.getByRole("menuitem", { name: translations.actions.enable, exact: true }).click();
    await expect.poll(async () => (await (await context.request.get(catalogUrl)).json()).services.find((service: { id: string }) => service.id === saved.id).active).toBe(true);

    await page.goto(`${baseURL}/agent/rules`);
    await page.getByRole("button", { name: translations.sections.rules.addKnowledge, exact: true }).click();
    await dialog.getByLabel(translations.sections.rules.fields.title.label, { exact: true }).fill("Callback rule");
    await dialog.getByLabel(translations.sections.rules.fields.content.label, { exact: true }).fill("Ask the caller for their preferred callback time.");
    await dialog.getByRole("button", { name: translations.actions.save, exact: true }).click();
    await expect(dialog).toBeHidden();
    await page.reload();
    await expect(page.getByText("Callback rule", { exact: true })).toBeVisible();
    await page.getByRole("row").filter({ hasText: "Callback rule" }).getByRole("button", { name: translations.actions.moreOptions }).click();
    await page.getByRole("menuitem", { name: translations.actions.delete, exact: true }).click();
    await page.getByRole("alertdialog").getByRole("button", { name: translations.actions.deleteCancel, exact: true }).click();
    await expect(page.getByText("Callback rule", { exact: true })).toBeVisible();
    await page.getByRole("row").filter({ hasText: "Callback rule" }).getByRole("button", { name: translations.actions.moreOptions }).click();
    await page.getByRole("menuitem", { name: translations.actions.delete, exact: true }).click();
    await page.getByRole("alertdialog").getByRole("button", { name: translations.actions.delete, exact: true }).click();
    await expect(page.getByText("Callback rule", { exact: true })).toBeHidden();

    await page.goto(`${baseURL}/agent/knowledge`);
    await page.getByRole("button", { name: translations.sections.knowledge.addKnowledge, exact: true }).click();
    await page.getByRole("menuitem", { name: translations.sections.knowledge.addKnowledgeOptions.text, exact: true }).click();
    await dialog.getByLabel(translations.sections.knowledge.fields.title.label, { exact: true }).fill("Clinic hours");
    await dialog.getByLabel(translations.sections.knowledge.fields.content.label, { exact: true }).fill("Open weekdays, 9 to 5.");
    await dialog.getByLabel(translations.sections.knowledge.fields.tags.label, { exact: true }).fill("clinic, hours");
    await dialog.getByRole("button", { name: translations.actions.save, exact: true }).click();
    await expect(dialog).toBeHidden();
    const snippetsUrl = `${baseURL}/api/knowledge/snippets?businessId=${businessId}`;
    const snippet = (await (await context.request.get(snippetsUrl)).json()).snippets[0];
    expect(snippet).toMatchObject({ title: "Clinic hours", tags: ["clinic", "hours"], priority: 75, active: true });
    await page.reload();
    await page.getByText("Clinic hours", { exact: true }).click();
    await expect(dialog.getByLabel(translations.sections.knowledge.fields.tags.label, { exact: true })).toHaveValue("clinic, hours");
    await dialog.getByLabel(translations.sections.knowledge.fields.tags.label, { exact: true }).fill("policy");
    await dialog.getByRole("button", { name: translations.actions.saveChanges, exact: true }).click();
    await expect(dialog).toBeHidden();
    expect((await (await context.request.get(snippetsUrl)).json()).snippets[0].tags).toEqual(["policy"]);
    await page.getByRole("row").filter({ hasText: "Clinic hours" }).getByRole("button", { name: translations.actions.moreOptions }).click();
    await page.getByRole("menuitem", { name: translations.actions.disable, exact: true }).click();
    await expect.poll(async () => (await (await context.request.get(snippetsUrl)).json()).snippets[0].active).toBe(false);

    const notificationUrl = `${baseURL}/api/notification-preferences?businessId=${businessId}`;
    const initialPreferences = await (await context.request.get(notificationUrl)).json();
    expect((await context.request.put(notificationUrl, { headers, data: { ...initialPreferences, smsEnabled: true, smsConsent: true } })).status()).toBe(400);
    await auth.db.update(users).set({ phone: "+14165550901", phoneVerifiedAt: new Date() }).where(eq(users.id, userId!));
    await withBusinessTransaction(database.db, { businessId, actorType: "worker" }, async tx => tx.insert(phoneNumbers).values({ businessId, e164: `+1416555${String(parseInt(businessId.slice(0, 4), 16) % 10000).padStart(4, "0")}`, status: "active", voiceEnabled: true, smsEnabled: true }));
    await page.goto(`${baseURL}/settings/notifications`);
    const smsSwitch = page.getByRole("switch", { name: settings.notifications.sources.sms.title, exact: true });
    await expect(smsSwitch).toBeEnabled();
    await smsSwitch.click();
    await expect(dialog.getByRole("heading", { name: settings.notifications.smsConsent.title, exact: true })).toBeVisible();
    await dialog.getByRole("button", { name: settings.notifications.smsConsent.cancel, exact: true }).click();
    expect((await (await context.request.get(notificationUrl)).json()).smsConsent).toBe(false);
    await smsSwitch.click();
    await dialog.getByRole("button", { name: settings.notifications.smsConsent.accept, exact: true }).click();
    await expect(dialog).toBeHidden();
    await expect.poll(async () => (await (await context.request.get(notificationUrl)).json()).smsConsent).toBe(true);
    await page.reload();
    await expect(smsSwitch).toBeChecked();
    await smsSwitch.click();
    await expect.poll(async () => (await (await context.request.get(notificationUrl)).json()).smsEnabled).toBe(false);

    await withBusinessTransaction(database.db, { businessId, actorType: "worker" }, async (tx) => tx.update(businessMemberships).set({ role: "viewer" }).where(eq(businessMemberships.businessId, businessId)));
    await page.goto(`${baseURL}/agent/services`);
    await expect(page.getByText("Updated consultation", { exact: true })).toBeVisible();
    await expect(page.getByRole("button", { name: translations.sections.services.addKnowledge, exact: true })).toBeHidden();
    expect((await context.request.patch(`${baseURL}/api/catalog/${saved.id}?businessId=${businessId}`, { headers, data: { active: false } })).status()).toBe(403);
    expect((await context.request.post(`${baseURL}/api/rules?businessId=${businessId}`, { headers, data: { title: "Denied", content: "Denied" } })).status()).toBe(403);
    expect((await context.request.patch(`${baseURL}/api/knowledge/snippets/${snippet.id}?businessId=${businessId}`, { headers, data: { tags: ["denied"] } })).status()).toBe(403);
    await page.goto(`${baseURL}/agent/knowledge?setup=website`);
    await expect(page.getByRole("button", { name: translations.sections.knowledge.addKnowledge, exact: true })).toBeHidden();
    await expect(page.getByRole("dialog")).toBeHidden();
  } finally {
    await context.close();
    await auth.db.update(users).set({ activeBusinessId: original?.activeBusinessId ?? null, phone: original?.phone ?? null, phoneVerifiedAt: original?.phoneVerifiedAt ?? null }).where(eq(users.id, userId!));
    await withBusinessTransaction(database.db, { businessId, actorType: "worker" }, async (tx) => tx.delete(businesses).where(eq(businesses.id, businessId)));
    await Promise.all([database.pool.end(), auth.pool.end()]);
  }
});
