import { oauthProviderAuthServerMetadata } from "@better-auth/oauth-provider";

import { getAuth } from "../auth";
import { protectedResourceMetadata } from "./oauth-config";

// Discovery documents for MCP clients. Browser-based clients (the MCP
// Inspector, for example) read them cross-origin, so they allow any origin.
// They carry no credentials and no user data.

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Methods": "GET, OPTIONS",
  "Access-Control-Allow-Headers": "mcp-protocol-version, content-type",
  "Cache-Control": "public, max-age=300",
};

export function metadataOptions(): Response {
  return new Response(null, { status: 204, headers: { ...corsHeaders, "Access-Control-Max-Age": "86400" } });
}

/** RFC 9728 Protected Resource Metadata for /api/mcp. */
export function protectedResourceMetadataResponse(): Response {
  return Response.json(protectedResourceMetadata(), { headers: corsHeaders });
}

/** RFC 8414 Authorization Server Metadata, generated by the oauth-provider plugin. */
export async function authorizationServerMetadataResponse(request: Request): Promise<Response> {
  const response = await oauthProviderAuthServerMetadata(getAuth(), { headers: corsHeaders })(request);
  return response;
}
