import { ArrowLeft, Clock3, Download, MessageSquareText, PhoneCall } from "lucide-react";
import Link from "next/link";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export default async function CallDetailPage({ params }: { params: Promise<{ callId: string }> }) {
  const { callId } = await params;
  return <div className="space-y-8"><Link className="inline-flex items-center gap-2 text-sm font-medium text-slate-500 hover:text-slate-900" href="/calls"><ArrowLeft className="size-4" />Back to calls</Link><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-teal-700">Call detail</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">Maya Chen</h1><p className="mt-2 text-sm text-slate-500">Call {callId} · Today at 09:12</p></div><div className="flex gap-3"><Button variant="outline"><Download className="size-4" />Download recording</Button><Button><PhoneCall className="size-4" />Call back</Button></div></div><div className="grid gap-6 xl:grid-cols-[0.7fr_1.3fr]"><Card><CardHeader><CardTitle>Call summary</CardTitle><CardDescription>Structured outcome from the receptionist.</CardDescription></CardHeader><CardContent className="space-y-4"><Info icon={Clock3} label="Duration" value="04:18" /><Info icon={PhoneCall} label="Outcome" value="Appointment booked" /><Info icon={MessageSquareText} label="Service" value="General checkup" /></CardContent></Card><Card><CardHeader><CardTitle>Transcript</CardTitle><CardDescription>Customer content stays in PostgreSQL and is never sent to operational telemetry.</CardDescription></CardHeader><CardContent className="space-y-5">{[["Assistant", "Thank you for calling Maple Family Clinic. How can I help today?"], ["Maya Chen", "I would like to schedule a general checkup next week."], ["Assistant", "I found an opening on Tuesday at 9:30 AM. Would you like me to book that for you?"], ["Maya Chen", "Yes, that works." ]].map(([speaker, text]) => <div className="flex gap-3" key={`${speaker}-${text}`}><span className="mt-1 grid size-8 shrink-0 place-items-center rounded-full bg-slate-100 text-xs font-semibold text-slate-600">{speaker?.[0] ?? "?"}</span><div><p className="text-xs font-semibold uppercase tracking-wide text-slate-400">{speaker}</p><p className="mt-1 text-sm leading-6 text-slate-700">{text}</p></div></div>)}</CardContent></Card></div></div>;
}

function Info({ icon: Icon, label, value }: { icon: typeof Clock3; label: string; value: string }) { return <div className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><Icon className="size-4 text-teal-700" /><div><p className="text-xs text-slate-500">{label}</p><p className="text-sm font-medium text-slate-900">{value}</p></div></div>; }
