'use strict';

// Samples and output fields for the v1 resources. Webhook payloads carry the
// same objects in `data`, so triggers, actions and searches share them.

const samples = {
  business: {
    id: '5b0f3c3e-2f7a-4c2e-9d8b-1f0a9b6c7d21',
    name: 'Maple Street Dental',
    timezone: 'America/Toronto',
    locale: 'en',
    website_url: 'https://maplestreetdental.example.com',
    booking_mode: 'instant',
    hours: [{ day: 'monday', open: '09:00', close: '17:00' }],
    created_at: '2026-01-12T14:03:22Z',
    updated_at: '2026-09-01T18:45:10Z',
  },
  service: {
    id: '0d6c1f4e-8a3b-4b7e-9c2d-5e6f7a8b9c01',
    name: 'Cleaning',
    description: 'Routine cleaning and checkup.',
    duration_minutes: 60,
    created_at: '2026-01-12T14:10:00Z',
    updated_at: '2026-03-02T09:20:00Z',
  },
  call: {
    id: '7e2d4c6a-1b3f-4a5e-8d9c-0f1e2d3c4b5a',
    channel: 'phone',
    status: 'completed',
    outcome: 'appointment_booked',
    summary: 'Jordan Lee booked a cleaning for Tuesday at 10:00.',
    end_reason: 'caller_hung_up',
    contact_id: '3c9a1e7b-5d2f-4e8a-b6c4-9f0d1e2a3b4c',
    caller_name: 'Jordan Lee',
    caller_phone: '+14165550134',
    duration_seconds: 184,
    recording_available: true,
    started_at: '2026-09-22T15:02:11Z',
    ended_at: '2026-09-22T15:05:15Z',
    created_at: '2026-09-22T15:02:11Z',
  },
  contact: {
    id: '3c9a1e7b-5d2f-4e8a-b6c4-9f0d1e2a3b4c',
    name: 'Jordan Lee',
    phone: '+14165550134',
    email: 'jordan.lee@example.com',
    locale: 'en',
    timezone: 'America/Toronto',
    created_at: '2026-09-22T15:03:40Z',
    updated_at: '2026-09-22T15:03:40Z',
  },
  appointment: {
    id: '9a8b7c6d-5e4f-4a3b-8c2d-1e0f9a8b7c6d',
    status: 'confirmed',
    starts_at: '2026-09-29T14:00:00Z',
    ends_at: '2026-09-29T15:00:00Z',
    timezone: 'America/Toronto',
    service_id: '0d6c1f4e-8a3b-4b7e-9c2d-5e6f7a8b9c01',
    service_name: 'Cleaning',
    staff_id: '4f3e2d1c-0b9a-4876-a543-210fedcba987',
    staff_name: 'Dr. Priya Shah',
    contact_id: '3c9a1e7b-5d2f-4e8a-b6c4-9f0d1e2a3b4c',
    contact_name: 'Jordan Lee',
    contact_phone: '+14165550134',
    source: 'voice',
    calendar_sync_status: 'synced',
    created_at: '2026-09-22T15:04:02Z',
    updated_at: '2026-09-22T15:04:02Z',
  },
  message: {
    id: '2b4d6f8a-0c1e-4a3b-9d5f-7e9a1c3b5d7f',
    status: 'open',
    title: 'Callback about an invoice',
    body: 'Sam Rivera asked about the invoice from their last visit. Please call back this afternoon.',
    caller_name: 'Sam Rivera',
    callback_phone: '+14165550188',
    urgency: 'normal',
    callback_window: 'This afternoon',
    channel: 'voice',
    call_id: '7e2d4c6a-1b3f-4a5e-8d9c-0f1e2d3c4b5a',
    created_at: '2026-09-22T16:20:45Z',
    updated_at: '2026-09-22T16:20:45Z',
  },
  knowledgeEntry: {
    id: '6c5b4a39-2817-4f6e-8d5c-4b3a29181706',
    type: 'faq',
    title: 'Do you offer evening appointments?',
    content: 'Yes. We are open until 8 PM on Thursdays.',
    created_at: '2026-09-22T17:00:00Z',
  },
};

const outputFields = {
  call: [
    { key: 'id', label: 'Call ID', type: 'string' },
    { key: 'channel', label: 'Channel', type: 'string' },
    { key: 'status', label: 'Status', type: 'string' },
    { key: 'outcome', label: 'Outcome', type: 'string' },
    { key: 'summary', label: 'Summary', type: 'string' },
    { key: 'end_reason', label: 'End Reason', type: 'string' },
    { key: 'contact_id', label: 'Contact ID', type: 'string' },
    { key: 'caller_name', label: 'Caller Name', type: 'string' },
    { key: 'caller_phone', label: 'Caller Phone', type: 'string' },
    { key: 'duration_seconds', label: 'Duration (Seconds)', type: 'integer' },
    { key: 'recording_available', label: 'Recording Available', type: 'boolean' },
    { key: 'started_at', label: 'Started At', type: 'datetime' },
    { key: 'ended_at', label: 'Ended At', type: 'datetime' },
    { key: 'created_at', label: 'Created At', type: 'datetime' },
  ],
  contact: [
    { key: 'id', label: 'Contact ID', type: 'string' },
    { key: 'name', label: 'Name', type: 'string' },
    { key: 'phone', label: 'Phone', type: 'string' },
    { key: 'email', label: 'Email', type: 'string' },
    { key: 'locale', label: 'Language', type: 'string' },
    { key: 'timezone', label: 'Time Zone', type: 'string' },
    { key: 'created_at', label: 'Created At', type: 'datetime' },
    { key: 'updated_at', label: 'Updated At', type: 'datetime' },
  ],
  appointment: [
    { key: 'id', label: 'Appointment ID', type: 'string' },
    { key: 'status', label: 'Status', type: 'string' },
    { key: 'starts_at', label: 'Starts At', type: 'datetime' },
    { key: 'ends_at', label: 'Ends At', type: 'datetime' },
    { key: 'timezone', label: 'Time Zone', type: 'string' },
    { key: 'service_id', label: 'Service ID', type: 'string' },
    { key: 'service_name', label: 'Service Name', type: 'string' },
    { key: 'staff_id', label: 'Staff ID', type: 'string' },
    { key: 'staff_name', label: 'Staff Name', type: 'string' },
    { key: 'contact_id', label: 'Contact ID', type: 'string' },
    { key: 'contact_name', label: 'Contact Name', type: 'string' },
    { key: 'contact_phone', label: 'Contact Phone', type: 'string' },
    { key: 'source', label: 'Source', type: 'string' },
    { key: 'calendar_sync_status', label: 'Calendar Sync Status', type: 'string' },
    { key: 'created_at', label: 'Created At', type: 'datetime' },
    { key: 'updated_at', label: 'Updated At', type: 'datetime' },
  ],
  message: [
    { key: 'id', label: 'Message ID', type: 'string' },
    { key: 'status', label: 'Status', type: 'string' },
    { key: 'title', label: 'Title', type: 'string' },
    { key: 'body', label: 'Message', type: 'string' },
    { key: 'caller_name', label: 'Caller Name', type: 'string' },
    { key: 'callback_phone', label: 'Callback Phone', type: 'string' },
    { key: 'urgency', label: 'Urgency', type: 'string' },
    { key: 'callback_window', label: 'Callback Window', type: 'string' },
    { key: 'channel', label: 'Channel', type: 'string' },
    { key: 'call_id', label: 'Call ID', type: 'string' },
    { key: 'created_at', label: 'Created At', type: 'datetime' },
    { key: 'updated_at', label: 'Updated At', type: 'datetime' },
  ],
  knowledgeEntry: [
    { key: 'id', label: 'Entry ID', type: 'string' },
    { key: 'type', label: 'Type', type: 'string' },
    { key: 'title', label: 'Title', type: 'string' },
    { key: 'content', label: 'Content', type: 'string' },
    { key: 'created_at', label: 'Created At', type: 'datetime' },
  ],
};

module.exports = { samples, outputFields };
